### PR TITLE
added jsend specific methods

### PR DESCRIPTION
**Pull request by charlesmulder**

### CODE REVIEW

**Comment by evangraan** [comment]
Can you bump the gem version as well? (0.2.0)

Also, the README needs to be updated with the new usage (both usage sets in separate sections in the README)

**Comment by charlesmulder** [comment]
Ok cool. Done.

**Comment by evangraan** [comment]
Great, thanks. FYI, I prefer @variable = { 'some' => 'value' } instead of let.

Each example group in Rspec defines a custom class (think java inner class).  
:let defines an instant method on the class it is used in. How-ever, when a spec runs, the instance is of the custom class, not the class the :let was defined in.
Code in :let blocks is lazy-loaded, only executed when called.
I prefer using a proper factory, or constants, than :let functions that look like attributes. Where lazy-loading is important they could be useful, how-ever.
Constants are meant not to change, :let does allow an override :let later to change a value, so lets are not a good idea to model functions.
A group of lets at the top of a test, though easier to read perhaps, run the risk of becoming quite a large collection of definitions, which may not only be values, but blocks of code. I.e. dependencies might be hard to model in this flat structure, and functionality is made more procedural by using :let. I think it better to model the test functionality and values using factories.
:let is essentially a work-around for rspec's failure to embrace object orientation, and as such a substitute allowing developers to get away without addressing a real design need in their specs.

In this instance it is small and easy to maintain, but my preference would be for a proper variable none-the-less.

**Comment by evangraan** [comment]
Would you mind updating re: the above, then commit with a fixes #1 and fixes #2 in the commit message.  That way, when I merge, it closes the issues with traceability to the commits. Thanks for having done this and taking this gem forward!!

**Comment by evangraan** [comment]
Ps: please add yourself to the list of authors in the gem spec, with your hetzner email address following my example, and a link to your rubygems or github profile.

**Comment by charlesmulder** [comment]
Please see my attempt at implementing your suggestion. Not sure I clearly understand @ vs let. Please advise.

**Pull request merged**
